# Generated by Django 5.1.7 on 2025-04-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
